#include ./micustom.conf
include ./mocha.conf

# opacidad y desenfoque de fondo
background_opacity 0.80
background_blur 20

#Fuente
font_family  JetBrainsMono Nerd Font
#font_family   Hack Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
url_style curly

#cursor
cursor_shape beam

#scroll sensitivity touchpad
touch_scroll_multiplier 4.0

#Movimiento entre ventanas dentro de un mismo tab
map ctrl+up neighboring_window up
map ctrl+right neighboring_window right
map ctrl+down neighboring_window bottom
map ctrl+left neighboring_window left

#buscar palabra
map ctrl+shift+f search

#Movimiento entre tabs
# map ctrl+shift+ previous_tab
# map ctrl+l next_tab

# Close term sesion without confirm
confirm_os_window_close 0

#Mapear cortar pegar
map f1 copy_to_buffer a
map f2 paste_from_buffer a
map f3 copy_to_buffer b
map f4 paste_from_buffer b

#Diseño de ventana
window_padding_width  13 
window_marging_width  13

tab_title_template "{index} {title}"

# Alineación de la barra de pestañas: left, center, right
tab_bar_align left

tab_bar_edge top
# Estilo de la barra de pestañas: fade, slant, powerline
tab_bar_style powerline
# Si el estilo que seleccionaste es powerline, puedes hacer otras modificaciones
# angled, slanted, round
tab_powerline_style slanted
# Renombrar la pestaña

# Nueva ventan en le directorio actual 
map ctrl+shift+enter launch --cwd=current

map alt+r set_tab_title

# Para abrir una nueva tab desde un script
allow_remote_control yes


