# Fondo más oscuro (modo server)
background #16161e
foreground #c0caf5

# Cursor más visible
cursor #ff9e64

# Barra superior distinta
tab_bar_style powerline
active_tab_foreground #1a1b26
active_tab_background #7aa2f7
