wallpaper {
    monitor = eDP-1
    # path = ~/Hyprland-Dots/wallpapers/Lofi\ -\ Study.png
    # path = ~/Hyprland-Dots/wallpapers/Fuji-Dark.png
    # path = ~/Hyprland-Dots/wallpapers/dark-souls-bonfire-scene-wallpaper-4k.jpg
    # path = /home/mario/wallpapers/4k-red-japanese-mountain-painting-ai-generated-4k-wallpaper.jpg
    # path = /home/mario/wallpapers/2026-01-18-fe20ab7d-25f4-4040-a132-f67a145f0b24.jpg
    # path = /home/mario/wallpapers/4k-ancient-temple-red-foliage-japanese-art-wallpaper.jpg
    path = /home/mario/wallpapers/Wallpapers/mafu_trad_wall.png
    fit_mode = cover
}

splash = false



