wallpaper {
    monitor = 
    # path = ~/Hyprland-Dots/wallpapers/Lofi\ -\ Study.png
    # path = ~/Hyprland-Dots/wallpapers/Fuji-Dark.png
    # path = ~/Hyprland-Dots/wallpapers/dark-souls-bonfire-scene-wallpaper-4k.jpg
    path = ~/Hyprland-Dots/wallpapers/4k-red-japanese-mountain-painting-ai-generated-4k-wallpaper.jpg
    # path = ~/Hyprland-Dots/wallpapers/2026-01-18-fe20ab7d-25f4-4040-a132-f67a145f0b24.jpg
    # path = ~/Hyprland-Dots/wallpapers/4k-ancient-temple-red-foliage-japanese-art-wallpaper.jpg
    # path = ~/Hyprland-Dots/wallpapers/mafu_trad_wall.png
    # path = ~/Hyprland-Dots/wallpapers/Untitled.jpg
    path = ~/Hyprland-Dots/wallpapers/a_city_skyline_at_night.jpg
    # path = ~/Hyprland-Dots/wallpapers/a_bridge_with_lights_on_it.jpg
    fit_mode = cover
}

splash = false



