wallpaper {
    monitor = eDP-1
    # path = ~/dotfiles/wallpapers/Fuji-Dark.png
    # path = ~/wallpapers/misfondos/girl.jpg
    # path = ~/wallpapers/misfondos/urban-mysterious-lights-film-aesthetic.jpg
    # path = ~/wallpapers/misfondos/japanese-night-alley.jpg
    # path = /home/mario/wallpapers/Dynamic-Wallpapers/Dark/photo-1591221822042-8643a8cd6645.png 
    path = /home/mario/wallpapers/misfondos/dark-souls-bonfire-scene-wallpaper-4k.jpg
    fit_mode = cover
}

splash = false

# $route1 = /home/mario/wallpapers/Anime-Girl-Night-Sky.jpg
# $route2 = /home/mario/wallpapers/Anime-Girl1.png
# $route3 = /home/mario/wallpapers/Sunset-Forrest.png
# $route4 = /home/mario/wallpapers/City-Rain.png
# $route5 = /home/mario/wallpapers/Buildings.png
# $route6 = /home/mario/wallpapers/Dynamic-Wallpapers/Light/Mountain_light.png
# $route7 = /home/mario/wallpapers/Dynamic-Wallpapers/animated/anime-girl-rain.960x540.mp4
# $route8 = /home/mario/wallpapers/Linux-user-Room.png
# $route9 = /home/mario/wallpapers/tanjiro-kamado-gruv.jpg
# $route10 = /home/mario/wallpapers/my-neighbor-totoro-sunflowers.png
# $rotue11 = /home/mario/wallpapers/Kojiro.png
# $route12 = /home/mario/wallpapers/a6809ed91e6509ca20aa1d786d5a0dc5.jpg
# $route13 = /home/mario/wallpapers/Under_Starlit_Sky.png
# $route14 = /home/mario/wallpapers/Garage.jpg
# $route15 = /home/mario/wallpapers/s4vitar.png
# $route16 = /home/mario/wallpapers/Dynamic-Wallpapers/Dark/Fuji-Dark.png
# /home/mario/wallpapers/Dynamic-Wallpapers/Dark/photo-1591221822042-8643a8cd6645.png 

# preload = $route16
# wallpaper = , $route16

